version: '3'

services:
  angular-ssr:
    build: ./Frontend  # Ruta del proyecto Angular con SSR
    container_name: angular-ssr
    restart: always
    ports:
      - "4010:4000"
    links:
      - webnode
    volumes:
      - ./Frontend/:/app
  
  webnode:
    env_file: ./.env
    container_name: webnode
    restart: always
    build: ./Backend
    ports:
      - "3010:3001"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./Backend/:/app

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27020:27017"
networks:
  default:
    driver: bridge