version: '3'

services:
  webnode:
    env_file: ./.env
    container_name: node-api
    restart: always
    build: ./Backend
    ports:
      - "3002:3001"
    links:
      - mongo
    volumes:
      - ./Backend/:/app

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27020:27017"

  angular-ssr:
    build: ./Frontend  # Ruta del proyecto Angular con SSR
    container_name: angular-ssr
    ports:
      - "4000:4000"
    depends_on:
      - webnode
    environment:
      - API_URL=http://node-api:3001  # URL para que Angular se comunique con el backend de Node.js
    volumes:
      - ./Frontend/:/app